apiVersion: v1
kind: Service
metadata:
  name: __APP__
  namespace: __NS__
  labels:
    app: __APP__
spec:
  type: LoadBalancer
  selector:
    app: __APP__
  ports:
    - name: http
      port: 80
      targetPort: 8080
